#!/home/pi/.rvm/rubies/ruby-2.3.0/bin/ruby

twitter = { symbol: 'TWTR', down_price: 15, up_price: 25 }
twilio = { symbol: 'TWLO', down_price: 62, up_price: 75 }
bitcoin = { symbol: 'BTCUSD=X', down_price: 550, up_price: 700 }
#ethereum =

begin
  portfolio_list = [twitter, twilio, bitcoin]

  portfolio_list.each do |portfolio_item|
    symbol = portfolio_item[:symbol]
    down_price = portfolio_item[:down_price]
    up_price = portfolio_item[:up_price]


    stock = StockQuote::Stock.quote(symbol)
    last_trade_price = stock.last_trade_price_only

    # notification logic
    if  last_trade_price <= down_price
      puts "#{symbol} was just traded under the down price limit you set at #{down_price}. Last registered trade was at: #{last_trade_price}\n"
    elsif last_trade_price >= up_price
      puts "#{symbol} was just traded over the up price limit you set at #{up_price}. Last registered trade was at: #{last_trade_price}\n"
    else
      #puts "#{symbol} is being traded within the limits you defined: Last registered trade: #{last_trade_price}. down price: #{down_price} / up price: #{up_price}\n"
    end

  end

rescue => e
  File.open('/home/pi/ruby_scripts/stock_notifications/stock_quote_errors.txt', 'a+') { |file| file.write("#{Time.now}: #{e.inspect}\n\n") }
end